export default [
    {'text':'Accommodation (Ariff) ','value':'1'},
{'text':'Accommodation (Cm) ','value':'1'},
{'text':'Accommodation (Enin)','value':'1'},
{'text':'Accommodation (Rachel) ','value':'1'},
{'text':'Accommodation (wx) ','value':'1'},
{'text':'Airbnb dec','value':'1'},
{'text':'Alcohol','value':'4'},
{'text':'Alita','value':'1'},
{'text':'Allergy','value':'1'},
{'text':'Andrew ','value':'2'},
{'text':'Andrew + Ray ','value':'1'},
{'text':'Angpau','value':'6'},
{'text':'Angpau ','value':'2'},
{'text':'Ankle guards ','value':'1'},
{'text':'Ant man','value':'1'},
{'text':'Arduino','value':'1'},
{'text':'Arduino ','value':'4'},
{'text':'Ariff ','value':'1'},
{'text':'Ariff ebook','value':'1'},
{'text':'Audio splitter ','value':'1'},
{'text':'Badminton ','value':'1'},
{'text':'Bag','value':'2'},
{'text':'Bali currency','value':'1'},
{'text':'Banana with tony ','value':'1'},
{'text':'Band-aid','value':'1'},
{'text':'Bank Islam deposit ','value':'1'},
{'text':'Bank islam parking','value':'2'},
{'text':'Basketball ','value':'1'},
{'text':'Basketball shoes','value':'2'},
{'text':'Bball arcade','value':'1'},
{'text':'Bball Shoes ','value':'3'},
{'text':'Bbq','value':'1'},
{'text':'Beer','value':'1'},
{'text':'Black whale','value':'1'},
{'text':'Blinds ','value':'1'},
{'text':'Board games','value':'4'},
{'text':'Bob','value':'3'},
{'text':'Bob + ck','value':'3'},
{'text':'Book ','value':'1'},
{'text':'Booze party','value':'1'},
{'text':'Borderlands ','value':'1'},
{'text':'Bottle ','value':'1'},
{'text':'Bowling ','value':'1'},
{'text':'BR1M','value':'1'},
{'text':'Bread','value':'3'},
{'text':'Bread ','value':'2'},
{'text':'Breakfast (168)','value':'1'},
{'text':'Breakfast (bread) ','value':'1'},
{'text':'Breakfast (burger King) ','value':'3'},
{'text':'Breakfast (chicken rice) ','value':'1'},
{'text':'Breakfast (chipsmore) ','value':'1'},
{'text':'Breakfast (drinks) ','value':'2'},
{'text':'Breakfast (horlicks) ','value':'1'},
{'text':'Breakfast (Maggie) ','value':'1'},
{'text':'Breakfast (mamak) ','value':'1'},
{'text':'Breakfast (mcd) ','value':'4'},
{'text':'Breakfast (new hollywood) ','value':'1'},
{'text':'Breakfast (noodles) ','value':'5'},
{'text':'Breakfast (twiggies) ','value':'1'},
{'text':'Breakfast (wantan mee) ','value':'1'},
{'text':'Breakfast doughnuts','value':'1'},
{'text':'Broga trip','value':'3'},
{'text':'Bumper bracket','value':'1'},
{'text':'Bus to kl sentral ','value':'2'},
{'text':'Bus to klia','value':'3'},
{'text':'Cable ','value':'2'},
{'text':'Cake ','value':'1'},
{'text':'Can you keep a Secret ','value':'1'},
{'text':'Cap','value':'7'},
{'text':'Car battery ','value':'2'},
{'text':'Car brake','value':'1'},
{'text':'Car charger','value':'1'},
{'text':'Car seat cover','value':'1'},
{'text':'Chair','value':'1'},
{'text':'Chariofare','value':'1'},
{'text':'Chocolate','value':'1'},
{'text':'Christmas (bball kids) ','value':'2'},
{'text':'Christmas (kv) ','value':'1'},
{'text':'Christmas lights ','value':'1'},
{'text':'Chromecast ','value':'1'},
{'text':'Chun yong ','value':'1'},
{'text':'Chun yong pt3 maths ','value':'1'},
{'text':'Citta mall parking ','value':'1'},
{'text':'Cj','value':'2'},
{'text':'Ck','value':'1'},
{'text':'Ck & Cz','value':'1'},
{'text':'Cm owe','value':'1'},
{'text':'Cny clothes ','value':'1'},
{'text':'Coffee ','value':'3'},
{'text':'Cologne','value':'1'},
{'text':'Condense milk','value':'1'},
{'text':'Controller ','value':'1'},
{'text':'Credit card ','value':'1'},
{'text':'Cz','value':'2'},
{'text':'Cz ','value':'2'},
{'text':'Cz bottle','value':'1'},
{'text':'Cz cake ','value':'1'},
{'text':'Cz dumbbell','value':'2'},
{'text':'Cz leg','value':'1'},
{'text':'Cz phone cover','value':'3'},
{'text':'Cz work','value':'1'},
{'text':'Daboba','value':'3'},
{'text':'Dad','value':'7'},
{'text':'Dad reload ','value':'1'},
{'text':'Darts','value':'1'},
{'text':'Dashcam','value':'1'},
{'text':'Dead by daylight ','value':'1'},
{'text':'Deadpool 2','value':'1'},
{'text':'Deodorant','value':'2'},
{'text':'Dinner (18noma)','value':'1'},
{'text':'Dinner (a&w) ','value':'1'},
{'text':'Dinner (Ara Vietnamese) ','value':'1'},
{'text':'Dinner (Arabian) ','value':'1'},
{'text':'Dinner (bak kut teh) ','value':'2'},
{'text':'Dinner (bat kin bat San) ','value':'1'},
{'text':'Dinner (bens) ','value':'1'},
{'text':'Dinner (bookmark coffee) ','value':'1'},
{'text':'Dinner (briyani) ','value':'1'},
{'text':'Dinner (burger king) ','value':'1'},
{'text':'Dinner (burger lab with bball ppl) ','value':'2'},
{'text':'Dinner (burger lab) ','value':'1'},
{'text':'Dinner (caffe abnormal) ','value':'1'},
{'text':'Dinner (Carls junior) ','value':'1'},
{'text':'Dinner (changkat) ','value':'1'},
{'text':'Dinner (char kuey tiow ) ','value':'1'},
{'text':'Dinner (chee cheong fun) ','value':'4'},
{'text':'Dinner (chizu) ','value':'1'},
{'text':'Dinner (claypot chicken rice) ','value':'1'},
{'text':'Dinner (dai sum yun) ','value':'1'},
{'text':'Dinner (Daves deli) ','value':'1'},
{'text':'Dinner (dishes) ','value':'1'},
{'text':'Dinner (doni) ','value':'1'},
{'text':'Dinner (Eddie & Co) ','value':'1'},
{'text':'Dinner (f2f) ','value':'1'},
{'text':'Dinner (family mart) ','value':'1'},
{'text':'Dinner (foodpanda) ','value':'1'},
{'text':'Dinner (fried laksa) ','value':'1'},
{'text':'Dinner (hainan) ','value':'1'},
{'text':'Dinner (heartbeat) ','value':'2'},
{'text':'Dinner (hiong pan) ','value':'4'},
{'text':'Dinner (hokkien mee) ','value':'1'},
{'text':'Dinner (hong kong restaurant) ','value':'3'},
{'text':'Dinner (kanna) ','value':'1'},
{'text':'Dinner (kgb) ','value':'1'},
{'text':'Dinner (korean bbq) ','value':'2'},
{'text':'Dinner (korean) ','value':'1'},
{'text':'Dinner (lu rou) ','value':'1'},
{'text':'Dinner (maistreet) ','value':'1'},
{'text':'Dinner (malay store with jy)','value':'1'},
{'text':'Dinner (murni) ','value':'2'},
{'text':'Dinner (nasi lemak) ','value':'1'},
{'text':'Dinner (noodles) ','value':'1'},
{'text':'Dinner (Nyonya) ','value':'1'},
{'text':'Dinner (oasis) ','value':'1'},
{'text':'Dinner (one Utama) ','value':'2'},
{'text':'Dinner (pasar malam) ','value':'1'},
{'text':'Dinner (pho) ','value':'1'},
{'text':'Dinner (pizza lab) ','value':'1'},
{'text':'Dinner (pizza) ','value':'3'},
{'text':'Dinner (popo kitchen) ','value':'1'},
{'text':'Dinner (qtaro) ','value':'1'},
{'text':'Dinner (quan) ','value':'6'},
{'text':'Dinner (rekindle) ','value':'1'},
{'text':'Dinner (renaissance) ','value':'1'},
{'text':'Dinner (rendezvous) ','value':'1'},
{'text':'Dinner (saga) ','value':'6'},
{'text':'Dinner (sakae sushi) ','value':'1'},
{'text':'Dinner (seafood buffet with bball ppl) ','value':'1'},
{'text':'Dinner (sentul) ','value':'1'},
{'text':'Dinner (shabushabu) ','value':'2'},
{'text':'Dinner (shisha) ','value':'4'},
{'text':'Dinner (spades) ','value':'2'},
{'text':'Dinner (spaghetti) ','value':'1'},
{'text':'Dinner (steamboat) ','value':'1'},
{'text':'Dinner (sukiya) ','value':'1'},
{'text':'Dinner (sushi mentai) ','value':'2'},
{'text':'Dinner (sushi tei)','value':'1'},
{'text':'Dinner (sweet Inn) ','value':'1'},
{'text':'Dinner (Table & Apron) ','value':'1'},
{'text':'Dinner (tea Garden) ','value':'1'},
{'text':'Dinner (texas) ','value':'1'},
{'text':'Dinner (Thai bbq) ','value':'1'},
{'text':'Dinner (Thai in mookata) ','value':'1'},
{'text':'Dinner (Thai) ','value':'1'},
{'text':'Dinner (the brew house) ','value':'1'},
{'text':'Dinner (the teh tarik place) ','value':'1'},
{'text':'Dinner (The times) ','value':'1'},
{'text':'Dinner (toast & roast) ','value':'1'},
{'text':'Dinner (twiggies) ','value':'4'},
{'text':'Dinner (uncle Don) ','value':'1'},
{'text':'Dinner (Union roastery) ','value':'1'},
{'text':'Dinner (uspizza) ','value':'1'},
{'text':'Dinner (vegetarian) ','value':'1'},
{'text':'Dinner (western) ','value':'3'},
{'text':'Dinner (yakiniku) ','value':'1'},
{'text':'Dinner (zen) ','value':'1'},
{'text':'Dinner chago','value':'2'},
{'text':'Dinner chicken rice ','value':'3'},
{'text':'Dinner Chinese mamak ','value':'5'},
{'text':'Dinner kbbq','value':'1'},
{'text':'Dinner kkmart','value':'1'},
{'text':'Dinner korean bbq with seraya ','value':'1'},
{'text':'Dinner mamak','value':'74'},
{'text':'Dinner mamak ','value':'260'},
{'text':'Dinner mamak zapfan','value':'13'},
{'text':'Dinner mcd','value':'17'},
{'text':'Dinner oregi','value':'1'},
{'text':'Dinner panmee','value':'7'},
{'text':'Dinner panmee ','value':'12'},
{'text':'Dinner phostreet','value':'1'},
{'text':'Dinner porridge ','value':'1'},
{'text':'Dinner starling ','value':'2'},
{'text':'Dinner subway','value':'1'},
{'text':'Dinner teppanyaki','value':'1'},
{'text':'Dinner thai','value':'16'},
{'text':'Dinner tomyam','value':'2'},
{'text':'Donation (funeral) ','value':'2'},
{'text':'Donation (toddler heart surgery) ','value':'1'},
{'text':'Dr K mental health module','value':'1'},
{'text':'Drinks','value':'3'},
{'text':'Drinks CJ ','value':'1'},
{'text':'Drinks potluck ','value':'1'},
{'text':'Earphones ','value':'9'},
{'text':'Earrings ','value':'1'},
{'text':'Ed Sheeran concert ','value':'1'},
{'text':'Elaine','value':'1'},
{'text':'Elaine ','value':'2'},
{'text':'Electric Toothbrush ','value':'1'},
{'text':'Enin christmas gift (tealive) ','value':'1'},
{'text':'Enin graduation flowers','value':'1'},
{'text':'Ethernet cable','value':'1'},
{'text':'Face mask','value':'1'},
{'text':'Family mart ','value':'1'},
{'text':'Fever','value':'1'},
{'text':'Fish oil','value':'1'},
{'text':'Fix shoes','value':'4'},
{'text':'Forest ','value':'1'},
{'text':'Frame','value':'1'},
{'text':'Fu cha ','value':'1'},
{'text':'G2000 pants ','value':'1'},
{'text':'Gabriel ','value':'1'},
{'text':'Gamble','value':'2'},
{'text':'Genting ','value':'1'},
{'text':'Glasses ','value':'2'},
{'text':'Gloves ','value':'1'},
{'text':'Go noodles lunch','value':'1'},
{'text':'Godzilla','value':'1'},
{'text':'Grab','value':'7'},
{'text':'Grab (klia) ','value':'2'},
{'text':'Graduation photo','value':'1'},
{'text':'Graduation ticket','value':'1'},
{'text':'Hanoi ','value':'2'},
{'text':'Hanoi King ','value':'1'},
{'text':'Hanoi train','value':'1'},
{'text':'Hard drive ','value':'1'},
{'text':'Harry Potter ','value':'1'},
{'text':'Herbal tea ','value':'1'},
{'text':'High tea buffet','value':'1'},
{'text':'Hong kai April ','value':'1'},
{'text':'Hook','value':'2'},
{'text':'Hose clamp ','value':'1'},
{'text':'House ','value':'1'},
{'text':'House tax ','value':'2'},
{'text':'Ice cream','value':'2'},
{'text':'Ice pack','value':'1'},
{'text':'Icity ','value':'1'},
{'text':'Idealtech deposit ','value':'1'},
{'text':'Indecinelive','value':'1'},
{'text':'Insurance ','value':'1'},
{'text':'Ipoh','value':'2'},
{'text':'Ipoh breakfast ','value':'1'},
{'text':'IT ','value':'1'},
{'text':'Joker','value':'2'},
{'text':'Jumanji','value':'1'},
{'text':'Justin ','value':'5'},
{'text':'Karaoke ','value':'1'},
{'text':'Kek lapis','value':'1'},
{'text':'Kelly castle','value':'1'},
{'text':'Kenneth ','value':'3'},
{'text':'Keyboard ','value':'2'},
{'text':'Kf','value':'1'},
{'text':'Kf ','value':'1'},
{'text':'King','value':'3'},
{'text':'King ','value':'2'},
{'text':'Kv kk','value':'2'},
{'text':'Kyrios ','value':'1'},
{'text':'L.lunch (smores) ','value':'1'},
{'text':'Lacoste shoes','value':'1'},
{'text':'Last of Us','value':'1'},
{'text':'Lc','value':'3'},
{'text':'Lc bet','value':'1'},
{'text':'Lc Cable','value':'1'},
{'text':'Lc phone cover ','value':'1'},
{'text':'Leisure mall parking ','value':'1'},
{'text':'Lens','value':'1'},
{'text':'Lewis capaldi','value':'1'},
{'text':'Light bulb','value':'1'},
{'text':'LM ç™½é‡‘','value':'1'},
{'text':'LOL Tshirt ','value':'1'},
{'text':'Lowyat parking ','value':'1'},
{'text':'Luggage sorter mom ','value':'1'},
{'text':'Luna','value':'1'},
{'text':'Lunch (103 cafe) ','value':'1'},
{'text':'Lunch (aunty Annes) ','value':'1'},
{'text':'Lunch (bak kut teh) ','value':'2'},
{'text':'Lunch (bari uma) ','value':'1'},
{'text':'Lunch (bday cake) ','value':'1'},
{'text':'Lunch (bookmark Cafe) ','value':'1'},
{'text':'Lunch (bread) ','value':'2'},
{'text':'Lunch (brussels) ','value':'1'},
{'text':'Lunch (burger King) ','value':'10'},
{'text':'Lunch (burger lab) ','value':'3'},
{'text':'Lunch (burger on 16)','value':'1'},
{'text':'Lunch (burger) ','value':'1'},
{'text':'Lunch (butchers table) ','value':'1'},
{'text':'Lunch (butter chicken) ','value':'1'},
{'text':'Lunch (chee cheong fun) ','value':'5'},
{'text':'Lunch (chicken plus) ','value':'10'},
{'text':'Lunch (chicken rice) ','value':'59'},
{'text':'Lunch (chilli panmee) ','value':'2'},
{'text':'Lunch (cili panmee) ','value':'1'},
{'text':'Lunch (curee) ','value':'1'},
{'text':'Lunch (curry laksa) ','value':'1'},
{'text':'Lunch (dah makan) ','value':'2'},
{'text':'Lunch (dubuyo) ','value':'1'},
{'text':'Lunch (f2f) ','value':'1'},
{'text':'Lunch (farmers market) ','value':'1'},
{'text':'Lunch (fish ball noodles) ','value':'1'},
{'text':'Lunch (fish head noodles) ','value':'1'},
{'text':'Lunch (foodpanda) ','value':'4'},
{'text':'Lunch (fried rice) ','value':'1'},
{'text':'Lunch (fukiya) ','value':'1'},
{'text':'Lunch (gami) ','value':'1'},
{'text':'Lunch (hawker) ','value':'1'},
{'text':'Lunch (honey bunny) ','value':'1'},
{'text':'Lunch (ice cream quan) ','value':'1'},
{'text':'Lunch (kd) ','value':'2'},
{'text':'Lunch (kfc) ','value':'14'},
{'text':'Lunch (Kim gary) ','value':'5'},
{'text':'Lunch (kofix) ','value':'1'},
{'text':'Lunch (kompassion) ','value':'1'},
{'text':'Lunch (korean) ','value':'25'},
{'text':'Lunch (little fat duck) ','value':'1'},
{'text':'Lunch (mamak) ','value':'33'},
{'text':'Lunch (manhattan fish market) ','value':'1'},
{'text':'Lunch (marmalade) ','value':'1'},
{'text':'Lunch (mcd) ','value':'13'},
{'text':'Lunch (murni) ','value':'1'},
{'text':'Lunch (Nandos) ','value':'8'},
{'text':'Lunch (nasi ganja) ','value':'1'},
{'text':'Lunch (nasi kandar) ','value':'1'},
{'text':'Lunch (nasi lemak) ','value':'4'},
{'text':'Lunch (ninjajoe) ','value':'7'},
{'text':'Lunch (noodles) ','value':'4'},
{'text':'Lunch (oiso) ','value':'1'},
{'text':'Lunch (Orale) ','value':'1'},
{'text':'Lunch (panmee ) ','value':'4'},
{'text':'Lunch (pasta zanmai) ','value':'5'},
{'text':'Lunch (pau) ','value':'1'},
{'text':'Lunch (pizza mansion) ','value':'1'},
{'text':'Lunch (pizza) ','value':'4'},
{'text':'Lunch (plate and bowl) ','value':'1'},
{'text':'Lunch (pork noodles) ','value':'1'},
{'text':'Lunch (porridge) ','value':'1'},
{'text':'Lunch (powerplant) ','value':'8'},
{'text':'Lunch (RHB) ','value':'91'},
{'text':'Lunch (rib King) ','value':'3'},
{'text':'Lunch (sakura sushi) ','value':'1'},
{'text':'Lunch (secrets of louisiana) ','value':'1'},
{'text':'Lunch (semenyih) ','value':'1'},
{'text':'Lunch (shihlin) ','value':'1'},
{'text':'Lunch (smores) ','value':'13'},
{'text':'Lunch (soy) ','value':'1'},
{'text':'Lunch (spaghetti) ','value':'3'},
{'text':'Lunch (subway) ','value':'10'},
{'text':'Lunch (sukiya) ','value':'2'},
{'text':'Lunch (sushi zanmai) ','value':'1'},
{'text':'Lunch (taiko ramen) ','value':'1'},
{'text':'Lunch (tapestry) ','value':'1'},
{'text':'Lunch (texas) ','value':'5'},
{'text':'Lunch (Thai) ','value':'1'},
{'text':'Lunch (three little pigs) ','value':'2'},
{'text':'Lunch (toast and roast)','value':'2'},
{'text':'Lunch (toast and roast) ','value':'2'},
{'text':'Lunch (trec)','value':'5'},
{'text':'Lunch (udon) ','value':'1'},
{'text':'Lunch (uncle don) ','value':'1'},
{'text':'Lunch (wantan mee) ','value':'2'},
{'text':'Lunch (Wendys) ','value':'1'},
{'text':'Lunch (wong kok) ','value':'11'},
{'text':'Lunch (yeemee) ','value':'3'},
{'text':'Lunch (zap fan)','value':'97'},
{'text':'Lunch (zap fan) ','value':'12'},
{'text':'Lunch mamak','value':'2'},
{'text':'Lunch teh ais','value':'1'},
{'text':'Lunch with tony (ninjajoe) ','value':'1'},
{'text':'Macau tea ','value':'3'},
{'text':'Malaysian extra ','value':'1'},
{'text':'Mamak','value':'2'},
{'text':'Mamak with seraya ','value':'1'},
{'text':'Mandeep kickstarter','value':'1'},
{'text':'Marshall ear pad replacement','value':'1'},
{'text':'Mcd parking ','value':'1'},
{'text':'Mi band 3','value':'1'},
{'text':'Mi band 4','value':'1'},
{'text':'Mi soundbar','value':'1'},
{'text':'Miband strap','value':'1'},
{'text':'Milk','value':'1'},
{'text':'Mom','value':'24'},
{'text':'Mom ','value':'12'},
{'text':'Mom  vacuum bag','value':'1'},
{'text':'Mom bag ','value':'1'},
{'text':'Mom digi','value':'7'},
{'text':'Mom grab','value':'2'},
{'text':'Mom lazada','value':'3'},
{'text':'Mom mirror','value':'1'},
{'text':'Mom shirt','value':'3'},
{'text':'Mom shoerack','value':'1'},
{'text':'Mom table ','value':'1'},
{'text':'Mom trip','value':'2'},
{'text':'Mom tripod','value':'1'},
{'text':'Moms makeup','value':'1'},
{'text':'Monitor ','value':'2'},
{'text':'Monitor mount ','value':'1'},
{'text':'Monster','value':'1'},
{'text':'Mouse','value':'1'},
{'text':'Mousepad','value':'2'},
{'text':'Movie (aquaman) ','value':'1'},
{'text':'Movie (avengers) ','value':'1'},
{'text':'Movie (bohemian rhapsody) ','value':'1'},
{'text':'Movie (bumblebee) ','value':'1'},
{'text':'Movie (captain marvel) ','value':'1'},
{'text':'Movie (Dr doolittle) ','value':'1'},
{'text':'Movie (equalizer) ','value':'1'},
{'text':'Movie (holloween) ','value':'1'},
{'text':'Movie (incredibles) ','value':'1'},
{'text':'Movie (joker) ','value':'1'},
{'text':'Movie (MI6) ','value':'1'},
{'text':'Movie (mortal kombat) ','value':'1'},
{'text':'Movie (peninsula) ','value':'1'},
{'text':'Movie (spiderman) ','value':'1'},
{'text':'Movie (tenet) ','value':'1'},
{'text':'Movie (venom) ','value':'1'},
{'text':'Movie drinks','value':'1'},
{'text':'Movie tickets','value':'2'},
{'text':'Movie tickets for Mom and Friends ','value':'1'},
{'text':'Mrt','value':'1'},
{'text':'Muscle relaxer ','value':'1'},
{'text':'My town parking ','value':'3'},
{'text':'MyRapid','value':'1'},
{'text':'Nandos','value':'1'},
{'text':'Nba','value':'2'},
{'text':'Nyonya ','value':'1'},
{'text':'One de land','value':'1'},
{'text':'One Utama parking ','value':'3'},
{'text':'Organiser','value':'1'},
{'text':'Panadol ','value':'3'},
{'text':'Paper bag ','value':'1'},
{'text':'Parking','value':'7'},
{'text':'Parking ','value':'8'},
{'text':'Passport ','value':'1'},
{'text':'Peanut butter? ','value':'1'},
{'text':'Penalty ','value':'1'},
{'text':'Pendrive','value':'1'},
{'text':'Petrol','value':'14'},
{'text':'Petrol ','value':'83'},
{'text':'Phone','value':'2'},
{'text':'Phone holder','value':'1'},
{'text':'Phone screen ','value':'1'},
{'text':'Photobook','value':'2'},
{'text':'Photobook mom','value':'2'},
{'text':'Piercing ','value':'1'},
{'text':'Plant','value':'3'},
{'text':'Pool','value':'2'},
{'text':'Pool ','value':'4'},
{'text':'Popcorn ','value':'1'},
{'text':'Popo kitchen ','value':'1'},
{'text':'Powder','value':'1'},
{'text':'Programmable socket ','value':'1'},
{'text':'Ps4 spiderman ','value':'1'},
{'text':'Ptptn','value':'2'},
{'text':'Ptptn ','value':'27'},
{'text':'Puzzle ','value':'1'},
{'text':'Pyramid parking ','value':'1'},
{'text':'R&R Snacks ','value':'1'},
{'text':'Rack ','value':'1'},
{'text':'Rampage popcorn','value':'1'},
{'text':'Raymond ','value':'2'},
{'text':'Ready Player One','value':'1'},
{'text':'Redbull','value':'1'},
{'text':'Refund ','value':'1'},
{'text':'Reload ','value':'27'},
{'text':'Remember me','value':'1'},
{'text':'Remnant of the Ashes','value':'1'},
{'text':'Risk of Rain 2','value':'1'},
{'text':'Road tax','value':'2'},
{'text':'Roomba','value':'1'},
{'text':'Sakae sushi','value':'1'},
{'text':'Saman','value':'1'},
{'text':'Sambal ','value':'1'},
{'text':'Sasaran ','value':'1'},
{'text':'Screen protector ','value':'2'},
{'text':'Seraya','value':'4'},
{'text':'Seraya ','value':'2'},
{'text':'Service ','value':'3'},
{'text':'Sg dollar ','value':'1'},
{'text':'Shaver ','value':'1'},
{'text':'Shennice','value':'5'},
{'text':'Shingles ','value':'1'},
{'text':'Shirt','value':'8'},
{'text':'Shisha','value':'11'},
{'text':'Shisha ','value':'2'},
{'text':'Shoes ','value':'2'},
{'text':'Shopaholic abroad ','value':'1'},
{'text':'Shopee','value':'1'},
{'text':'Shuhui March ','value':'1'},
{'text':'Simcard','value':'1'},
{'text':'Snack (croissant) ','value':'2'},
{'text':'Snack (popiah) ','value':'1'},
{'text':'Snacks ','value':'11'},
{'text':'Socket ','value':'1'},
{'text':'Soldering kit ','value':'1'},
{'text':'Sore throat ','value':'2'},
{'text':'Spades burger','value':'2'},
{'text':'Specs ','value':'1'},
{'text':'Specs (first half) ','value':'1'},
{'text':'Specs (second half) ','value':'1'},
{'text':'Spiderman','value':'1'},
{'text':'Spotify','value':'2'},
{'text':'Spotify ','value':'36'},
{'text':'Spotify (ariff) ','value':'1'},
{'text':'Spray paint ','value':'3'},
{'text':'Starbucks','value':'1'},
{'text':'Starling Parking ','value':'2'},
{'text':'Stashaway ','value':'1'},
{'text':'Stationary ','value':'1'},
{'text':'Steam (hff & overcook)','value':'1'},
{'text':'Steam (NBA) ','value':'1'},
{'text':'Strepsils','value':'1'},
{'text':'Subang parade parking','value':'1'},
{'text':'Sunglasses ','value':'1'},
{'text':'Supper (family mart) ','value':'1'},
{'text':'Supper (hayaki) ','value':'1'},
{'text':'Supper (mamak + mcd) ','value':'1'},
{'text':'Supper (mamak) ','value':'2'},
{'text':'Supper (mcd) ','value':'1'},
{'text':'Supper mcd','value':'2'},
{'text':'Table','value':'1'},
{'text':'Tape','value':'1'},
{'text':'Tattoo','value':'1'},
{'text':'Tattoo deposit ','value':'1'},
{'text':'Tau fu fa','value':'1'},
{'text':'Tax refund ','value':'4'},
{'text':'Tealive','value':'1'},
{'text':'Tealive ','value':'3'},
{'text':'Texas with kk kv ken','value':'1'},
{'text':'Thai baht','value':'1'},
{'text':'The art of war','value':'1'},
{'text':'The working dead','value':'1'},
{'text':'Titanfall 2','value':'1'},
{'text':'TM Parking','value':'1'},
{'text':'Toll & petrol ','value':'1'},
{'text':'Toll back','value':'1'},
{'text':'Tony','value':'8'},
{'text':'Touch & Go','value':'16'},
{'text':'Touch & Go ','value':'13'},
{'text':'Transfer mom','value':'2'},
{'text':'Tuition ','value':'4'},
{'text':'Tuition (all) ','value':'2'},
{'text':'Tuition (books) ','value':'1'},
{'text':'Tuition (Chunyong Hong kai) ','value':'1'},
{'text':'Tuition (Chunyong) ','value':'3'},
{'text':'Tuition (hong hui) ','value':'3'},
{'text':'Tuition (hongkai) ','value':'2'},
{'text':'Tuition (replacement for Bs) ','value':'1'},
{'text':'Tuition (shuhui + claudia) ','value':'2'},
{'text':'Tuition (shuhui +books) ','value':'1'},
{'text':'Tuition (shuhui) ','value':'7'},
{'text':'Tuition (xin fei) ','value':'1'},
{'text':'Tuition books','value':'1'},
{'text':'Tuition Bs','value':'2'},
{'text':'Tuition Elaine ','value':'2'},
{'text':'Tuition rental','value':'2'},
{'text':'Tuition replacement Bs (April 18th)','value':'1'},
{'text':'Tuition replacement Bs (July 27th)','value':'1'},
{'text':'Tuition replacement Bs (July 6th)','value':'1'},
{'text':'Tuition replacement Bs (May 4th)','value':'1'},
{'text':'Tyres','value':'1'},
{'text':'Umobile ','value':'1'},
{'text':'Unilqlo denim shirt ','value':'1'},
{'text':'Unilqlo pants','value':'1'},
{'text':'USS ','value':'1'},
{'text':'Valheim','value':'1'},
{'text':'Vampire diaries','value':'1'},
{'text':'Viper (kk) ','value':'1'},
{'text':'Viper (syah) ','value':'1'},
{'text':'Viper challenge (darien gab syah kk) ','value':'1'},
{'text':'Viper challenge (darien justin) ','value':'1'},
{'text':'Wallet','value':'1'},
{'text':'Wallet ','value':'1'},
{'text':'Watch ','value':'1'},
{'text':'We were here','value':'1'},
{'text':'Wedding ','value':'3'},
{'text':'Whiteboard ','value':'1'},
{'text':'Wifi','value':'41'},
{'text':'Winter jacket ','value':'1'},
{'text':'Wx','value':'1'},
{'text':'Xin fu tang ','value':'1'},
{'text':'Yoga mat','value':'1'},
{'text':'Yoko yoko','value':'1'},
{'text':'Yomi','value':'1'},
{'text':'Ys book','value':'1'},
{'text':'Ys specs','value':'1'},
{'text':'Zippo','value':'1'},
{'text':'Zouk parking ','value':'54'},

]